### ISSUE TITLE
VirtualBox

### ISSUE THREAD

**Issue by MTSyntho** [datkat21/MiniOS#1]
i want to run it in VirtualBox but where .iso file?

**Comment by datkat21** [comment]
MiniOS is an application for Windows, not an a actual os. I called it MiniOS because it works like a sort of “mini ‘os’”.

You can download the windows exe file [here](https://github.com/datkat21/MiniOS/releases/download/v0.3/minios_v0-3.zip). The file is called `TestingWpfApp.exe` because that is the name of the visual studio project.
